Repository Rakshit-gen/Slanine, pull requests merged in 2024-10, with the labels that each got.

#23 fixed overflowing content bug
  app/dashboard/history/page.tsx
Labels: bug, gssoc, level 2, gssoc-ext

#33 #31 hero section text fix
  app/page.tsx
  components/Pricing.tsx
Labels: enhancement, gssoc, level 2, gssoc-ext

#42 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, level 1, gssoc-ext, hacktoberfest-accepted

#53 added github link to the footer
  components/Footer.tsx
Labels: bug, level 1, gssoc-ext, hacktoberfest-accepted

#96 added chatbot for enhanced user experience
  app/layout.tsx
  components/ScrollToTopButton.tsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#98 Added Table to Display Repository Statistics in README.md
  README.md
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#101 solved #99 Added Quiz section
  app/page.tsx
  components/QUIZ.tsx
  package-lock.json
  package.json
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#112 fixed padding in faq section
  components/FAQ.tsx
Labels: bug, level 2, gssoc-ext, hacktoberfest-accepted

#119 Add Movie Recommender
  app/(data)/Templates.tsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#120 Add Book Recommender Feature
  app/(data)/Templates.tsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#122 Add Sustainability Tracker Feature
  app/(data)/Templates.tsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#123 Add Event Networking Assistant Feature
  app/(data)/Templates.tsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#150 Fix: the subscribe to our newsletter is inaccessible #127
  components/ScrollToTopButton.tsx
Labels: bug, level 2, gssoc-ext, hacktoberfest-accepted

#158 added new ai tools for
  app/(data)/Templates.tsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#159 Add Social Media and Content Creation Tools
  app/(data)/Templates.tsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted
